# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Subgradient <- function(a, b, M, lambda, maxIter = 1000L, tolerance = 0.0001) {
    .Call('Barycenter_Subgradient', PACKAGE = 'Barycenter', a, b, M, lambda, maxIter, tolerance)
}

