# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SinkhornDistance <- function(a, b, costMatrix, lambda = 20, maxIter = 5000L, tolerance = 0.005) {
    .Call('_Barycenter_SinkhornDistance', PACKAGE = 'Barycenter', a, b, costMatrix, lambda, maxIter, tolerance)
}

Subgradient <- function(a, b, M, lambda, maxIter = 1000L, tolerance = 0.0001) {
    .Call('_Barycenter_Subgradient', PACKAGE = 'Barycenter', a, b, M, lambda, maxIter, tolerance)
}

